version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: chatapp_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: chatapp_db
      MYSQL_USER: chatapp_user
      MYSQL_PASSWORD: ProjP@ssw0rd!
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s

  redis:
    image: redis:7
    container_name: chatapp_redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
      start_period: 5s

  backend:
    build:
      context: ./chatapp_backend
      dockerfile: Dockerfile
    container_name: chatapp_backend
    restart: always
    command: >
      sh -c "sleep 10 && python manage.py migrate &&
      daphne -b 0.0.0.0 -p 8000 chatapp_backend.asgi:application"
    volumes:
      - ./chatapp_backend:/app
      - ./chatapp_backend/staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: chatapp_db
      DB_USER: chatapp_user
      DB_PASSWORD: ProjP@ssw0rd!
      GOOGLE_CLIENT_ID: "1055989923258-vvjhdbjqib8kj83nv8mbfbucofn7jcdh.apps.googleusercontent.com"
      GOOGLE_SECRET: "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"
      DJANGO_SETTINGS_MODULE: chatapp_backend.settings

  frontend:
    build:
      context: ./chatapp_frontend
      dockerfile: Dockerfile
    container_name: chatapp_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://backend:8000
      - VITE_WS_BASE_URL=ws://backend:8000
    volumes:
      - ./chatapp_frontend:/app
      - node_modules:/app/node_modules

volumes:
  mysql-data:
    driver: local
  node_modules: {}
