version: '3.8'

services:
  backend:
    build: ./chatapp_backend
    container_name: chatapp_backend
    ports:
      - "8000:8000"
    env_file:
      - ./chatapp_backend/.env  # Ensure you have an environment file for Django settings
    depends_on:
      - db
    networks:
      - chat_network

  frontend:
    build: ./chatapp_frontend
    container_name: chatapp_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - chat_network

  db:
    image: mysql:latest
    container_name: chatapp_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: chatapp
      MYSQL_USER: chatuser
      MYSQL_PASSWORD: chatpassword
    ports:
      - "3307:3306"
    networks:
      - chat_network

networks:
  chat_network:
    driver: bridge
