version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: chatapp_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: chatapp_db
      MYSQL_USER: chatapp_user
      MYSQL_PASSWORD: ProjP@ssw0rd!
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s

  backend:
    build:
      context: ./chatapp_backend  # Updated path
      dockerfile: Dockerfile
    container_name: chatapp_backend
    restart: always
    command: >
      sh -c "sleep 10 && python manage.py migrate && gunicorn chatapp_backend.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./chatapp_backend:/app  # Updated path
      - ./chatapp_backend/staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: chatapp_db
      DB_USER: chatapp_user
      DB_PASSWORD: ProjP@ssw0rd!
      GOOGLE_CLIENT_ID: "1055989923258-vvjhdbjqib8kj83nv8mbfbucofn7jcdh.apps.googleusercontent.com"
      GOOGLE_SECRET: "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"

  frontend:
    build:
      context: ./chatapp_frontend  # Updated path
      dockerfile: Dockerfile
    container_name: chatapp_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://backend:8000
    volumes:
      - ./chatapp_frontend:/app  # Updated path
      - node_modules:/app/node_modules  # Prevent overwriting installed dependencies

volumes:
  mysql-data:
    driver: local
  node_modules: {} 
